#!/bin/bash

clear
set -e

ENV_MODE="dev"
if [ "$1" == "--prod" ]; then
    ENV_MODE="prod"
    echo "Starting in PRODUCTION mode..."
else
    echo "Starting in DEVELOPMENT mode..."
fi

# ── Port assignment ─────────────────────────────────────────────────────────
# dev:  server=8000  ui=5173
# prod: server=8001  ui=1997
# Running both simultaneously is safe — they never share a port.
if [ "$ENV_MODE" == "prod" ]; then
    SERVER_PORT=8001
    UI_PORT=1997
    EXT_NAME="JOBVIS - (PROD)"
else
    SERVER_PORT=8000
    UI_PORT=5173
    EXT_NAME="JOBVIS - (DEV)"
fi

# ── Generate extension/config.js ─────────────────────────────────────────────
# This is the ONLY place where the port and env are defined.
# background.js and popup.js importScripts/load this file at runtime.
# Reload the extension in chrome://extensions after (re)starting.
cat > apps/extension/config.js << EOF
// Auto-generated by start.sh — do not edit manually.
// Regenerated each time ./start.sh [--prod] is run.
const API_BASE = 'http://localhost:${SERVER_PORT}';
const WS_BASE  = 'ws://localhost:${SERVER_PORT}';
const APP_ENV  = '${ENV_MODE}';
EOF

echo "✔ Generated apps/extension/config.js (env=${ENV_MODE}, port=${SERVER_PORT})"

# ── Update extension manifest name ───────────────────────────────────────────
# Stamp the manifest with the correct env name so chrome://extensions
# shows JOBVIS - (DEV) or JOBVIS - (PROD) clearly.
sed -i '' "s/\"JOBVIS - (DEV)\"/\"${EXT_NAME}\"/" apps/extension/manifest.json 2>/dev/null || true
sed -i '' "s/\"JOBVIS - (PROD)\"/\"${EXT_NAME}\"/" apps/extension/manifest.json 2>/dev/null || true

echo "✔ Extension name set to: ${EXT_NAME}"
echo ""

# Make sure child processes (the background server) die when this script is closed
trap 'kill 0' SIGINT SIGTERM EXIT

echo "========================================="
echo "   STARTING JOBVIS ($ENV_MODE) — server :$SERVER_PORT / ui :$UI_PORT"
echo "========================================="
echo ""

echo "[0/2] Starting Postgres Database via Docker..."
docker compose up -d
echo "Waiting a few seconds for DB to be configured..."
sleep 3
echo ""

echo "[1/2] Starting FastAPI Server on port $SERVER_PORT..."
cd apps/server

lsof -ti:$SERVER_PORT | xargs kill -9 2>/dev/null || true

APP_ENV=$ENV_MODE ./venv/bin/uvicorn main:app --reload --host 0.0.0.0 --port $SERVER_PORT --timeout-graceful-shutdown 3 &

cd ../..

echo "[2/2] Starting React Vite UI on port $UI_PORT..."
cd apps/ui
VITE_API_BASE="http://localhost:$SERVER_PORT" \
VITE_WS_BASE="ws://localhost:$SERVER_PORT" \
npm run dev -- --port $UI_PORT
